# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_auto_20150720_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='CiuOnHeatPump1',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
            ],
        ),
        migrations.CreateModel(
            name='CiuOnHeatPump2',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
            ],
        ),
        migrations.CreateModel(
            name='CiuOnHeatPump3',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
            ],
        ),
        migrations.CreateModel(
            name='CiuOnHeatPump4',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
            ],
        ),
        migrations.CreateModel(
            name='CiuOnHeatPump5',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
            ],
        ),
        migrations.CreateModel(
            name='CiuOnHeatPump6',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
            ],
        ),
        migrations.DeleteModel(
            name='OperationLogger',
        ),
        migrations.AddField(
            model_name='floor1ciu1',
            name='floor',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='floor1ciu10',
            name='floor',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='floor1ciu11',
            name='floor',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='floor1ciu12',
            name='floor',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='floor1ciu13',
            name='floor',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='floor1ciu14',
            name='floor',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='floor1ciu2',
            name='floor',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='floor1ciu3',
            name='floor',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='floor1ciu4',
            name='floor',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='floor1ciu5',
            name='floor',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='floor1ciu6',
            name='floor',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='floor1ciu7',
            name='floor',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='floor1ciu8',
            name='floor',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='floor1ciu9',
            name='floor',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='floor2ciu1',
            name='floor',
            field=models.SmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='floor2ciu10',
            name='floor',
            field=models.SmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='floor2ciu11',
            name='floor',
            field=models.SmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='floor2ciu12',
            name='floor',
            field=models.SmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='floor2ciu2',
            name='floor',
            field=models.SmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='floor2ciu3',
            name='floor',
            field=models.SmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='floor2ciu4',
            name='floor',
            field=models.SmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='floor2ciu5',
            name='floor',
            field=models.SmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='floor2ciu6',
            name='floor',
            field=models.SmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='floor2ciu7',
            name='floor',
            field=models.SmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='floor2ciu8',
            name='floor',
            field=models.SmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='floor2ciu9',
            name='floor',
            field=models.SmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='floor3ciu1',
            name='floor',
            field=models.SmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='floor3ciu10',
            name='floor',
            field=models.SmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='floor3ciu11',
            name='floor',
            field=models.SmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='floor3ciu12',
            name='floor',
            field=models.SmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='floor3ciu2',
            name='floor',
            field=models.SmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='floor3ciu3',
            name='floor',
            field=models.SmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='floor3ciu4',
            name='floor',
            field=models.SmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='floor3ciu5',
            name='floor',
            field=models.SmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='floor3ciu6',
            name='floor',
            field=models.SmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='floor3ciu7',
            name='floor',
            field=models.SmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='floor3ciu8',
            name='floor',
            field=models.SmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='floor3ciu9',
            name='floor',
            field=models.SmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='ciuonheatpump6',
            name='u1',
            field=models.ForeignKey(to='monitor.Floor3CIU2'),
        ),
        migrations.AddField(
            model_name='ciuonheatpump6',
            name='u2',
            field=models.ForeignKey(to='monitor.Floor3CIU3'),
        ),
        migrations.AddField(
            model_name='ciuonheatpump6',
            name='u3',
            field=models.ForeignKey(to='monitor.Floor3CIU4'),
        ),
        migrations.AddField(
            model_name='ciuonheatpump6',
            name='u4',
            field=models.ForeignKey(to='monitor.Floor3CIU5'),
        ),
        migrations.AddField(
            model_name='ciuonheatpump6',
            name='u5',
            field=models.ForeignKey(to='monitor.Floor3CIU6'),
        ),
        migrations.AddField(
            model_name='ciuonheatpump6',
            name='u6',
            field=models.ForeignKey(to='monitor.Floor3CIU7'),
        ),
        migrations.AddField(
            model_name='ciuonheatpump6',
            name='u7',
            field=models.ForeignKey(to='monitor.Floor3CIU8'),
        ),
        migrations.AddField(
            model_name='ciuonheatpump5',
            name='u1',
            field=models.ForeignKey(to='monitor.Floor1CIU6'),
        ),
        migrations.AddField(
            model_name='ciuonheatpump5',
            name='u2',
            field=models.ForeignKey(to='monitor.Floor1CIU7'),
        ),
        migrations.AddField(
            model_name='ciuonheatpump5',
            name='u3',
            field=models.ForeignKey(to='monitor.Floor1CIU8'),
        ),
        migrations.AddField(
            model_name='ciuonheatpump5',
            name='u4',
            field=models.ForeignKey(to='monitor.Floor1CIU9'),
        ),
        migrations.AddField(
            model_name='ciuonheatpump5',
            name='u5',
            field=models.ForeignKey(to='monitor.Floor1CIU10'),
        ),
        migrations.AddField(
            model_name='ciuonheatpump5',
            name='u6',
            field=models.ForeignKey(to='monitor.Floor1CIU11'),
        ),
        migrations.AddField(
            model_name='ciuonheatpump5',
            name='u7',
            field=models.ForeignKey(to='monitor.Floor1CIU12'),
        ),
        migrations.AddField(
            model_name='ciuonheatpump5',
            name='u8',
            field=models.ForeignKey(to='monitor.Floor1CIU13'),
        ),
        migrations.AddField(
            model_name='ciuonheatpump5',
            name='u9',
            field=models.ForeignKey(to='monitor.Floor1CIU14'),
        ),
        migrations.AddField(
            model_name='ciuonheatpump4',
            name='u1',
            field=models.ForeignKey(to='monitor.Floor1CIU1'),
        ),
        migrations.AddField(
            model_name='ciuonheatpump4',
            name='u2',
            field=models.ForeignKey(to='monitor.Floor1CIU2'),
        ),
        migrations.AddField(
            model_name='ciuonheatpump4',
            name='u3',
            field=models.ForeignKey(to='monitor.Floor1CIU3'),
        ),
        migrations.AddField(
            model_name='ciuonheatpump4',
            name='u4',
            field=models.ForeignKey(to='monitor.Floor1CIU4'),
        ),
        migrations.AddField(
            model_name='ciuonheatpump4',
            name='u5',
            field=models.ForeignKey(to='monitor.Floor1CIU5'),
        ),
        migrations.AddField(
            model_name='ciuonheatpump4',
            name='u6',
            field=models.ForeignKey(to='monitor.Floor2CIU1'),
        ),
        migrations.AddField(
            model_name='ciuonheatpump4',
            name='u7',
            field=models.ForeignKey(to='monitor.Floor3CIU1'),
        ),
        migrations.AddField(
            model_name='ciuonheatpump3',
            name='u1',
            field=models.ForeignKey(to='monitor.Floor2CIU2'),
        ),
        migrations.AddField(
            model_name='ciuonheatpump3',
            name='u2',
            field=models.ForeignKey(to='monitor.Floor2CIU3'),
        ),
        migrations.AddField(
            model_name='ciuonheatpump3',
            name='u3',
            field=models.ForeignKey(to='monitor.Floor2CIU4'),
        ),
        migrations.AddField(
            model_name='ciuonheatpump3',
            name='u4',
            field=models.ForeignKey(to='monitor.Floor2CIU5'),
        ),
        migrations.AddField(
            model_name='ciuonheatpump3',
            name='u5',
            field=models.ForeignKey(to='monitor.Floor2CIU6'),
        ),
        migrations.AddField(
            model_name='ciuonheatpump3',
            name='u6',
            field=models.ForeignKey(to='monitor.Floor2CIU7'),
        ),
        migrations.AddField(
            model_name='ciuonheatpump2',
            name='u1',
            field=models.ForeignKey(to='monitor.Floor2CIU8'),
        ),
        migrations.AddField(
            model_name='ciuonheatpump2',
            name='u2',
            field=models.ForeignKey(to='monitor.Floor2CIU9'),
        ),
        migrations.AddField(
            model_name='ciuonheatpump2',
            name='u3',
            field=models.ForeignKey(to='monitor.Floor2CIU10'),
        ),
        migrations.AddField(
            model_name='ciuonheatpump2',
            name='u4',
            field=models.ForeignKey(to='monitor.Floor2CIU11'),
        ),
        migrations.AddField(
            model_name='ciuonheatpump2',
            name='u5',
            field=models.ForeignKey(to='monitor.Floor2CIU12'),
        ),
        migrations.AddField(
            model_name='ciuonheatpump1',
            name='u1',
            field=models.ForeignKey(to='monitor.Floor3CIU9'),
        ),
        migrations.AddField(
            model_name='ciuonheatpump1',
            name='u2',
            field=models.ForeignKey(to='monitor.Floor3CIU10'),
        ),
        migrations.AddField(
            model_name='ciuonheatpump1',
            name='u3',
            field=models.ForeignKey(to='monitor.Floor3CIU11'),
        ),
        migrations.AddField(
            model_name='ciuonheatpump1',
            name='u4',
            field=models.ForeignKey(to='monitor.Floor3CIU12'),
        ),
    ]
